MAIN
{
	nbreiv : NATURAL;
	existe : NATURAL;
	ivmoy [30] : FLOAT;
	compteur : NATURAL;
	somme : FLOAT;
	nbadmis : NATURAL;
	secivmoy : FLOAT;
}
CODE
{
	$ k tablau ivmoy est trié
	nbreiv = 25;
	existe = 0 ;
	TANTQUE (compteur = 0 ,((compteur <= nbreiv) & (existe == 0)) , compteur = compteur = compteur+1)
	{
		VERIF(ivmoy[compteur] < 0)
		{
			existe = 1;
		}
		AUTRE
		{
			somme = somme + ivmoy[compteur];
		}
	}
nbadmis = compteur;
secivmoy = somme / compteur;
}
